### ISSUE TITLE
add date of issue created

### ISSUE THREAD

**Issue by heysujal** [heysujal/hacktoberfest-issue#9]
use `createdAt` from https://hacktoberfest-issues.herokuapp.com/issues to show the date of creation of issue

**Comment by heysujal** [comment]
@amritesh19  adding another column would be good I guess

**Comment by amritesh19** [comment]
@heysujal  Please merge it as soon as possible if it looks fine.
Browse the preview: https://deploy-preview-17--hacktoberfest-issues.netlify.app/

**Comment by amritesh19** [comment]
@heysujal Please merge it as soon as possible if it looks fine.
Browse the preview: https://deploy-preview-17--hacktoberfest-issues.netlify.app/
